### ISSUE TITLE
Отсутствуют символы греческого алфавита при использовании unicode-math

### ISSUE THREAD

**Issue by sergey-s-betke** [Metrolog/Font.GOST2.304-81#172]

**Comment by sergey-s-betke** [comment]
Проблема в том, что `Unicode-math` определяет `\Gamma` как `\mitGamma` (наклонные греческие символы для использования в математике, имеют отдельные Unicode позиции). Естественно, у меня в шрифте они не реализованы. И добавлять их в шрифт - есть ли смысл?

Стоит для начала поэкспериментировать с параметрами `Unicode-math`:

```
\PassOptionsToPackage
  {
    math-style = ISO,
    bold-style = ISO,
    % vargreek-shape = TeX,
    % colon = TeX,
    slash-delimiter = frac,
    active-frac = small
  }
  {unicode-math}
\RequirePackage{unicode-math}
```

Замена `\Greek` на `\textGreek` даёт результат. При этом используются действительно Unicode позиции символов греческого алфавита. И они есть в шрифте, они отображаются корректно. Однако, и с `\Gamma`, `\Alpha` и т.д. необходимо найти решение. Стоит подсмотреть реализацию в других шрифтах. Возможно, стоит при выборе шрифта переопределять макросы...

**Comment by sergey-s-betke** [comment]
Есть и ещё проблемы - с прописными символами греческого алфавита:
- [x] `\textgamma`. Судя по всему, используется http://unicode-table.com/ru/0263/, которого у меня нет в шрифте.
- [x] `\textepsilon`. Нужно определить символ `varepsilon`. TeX отправляет к нему при текущих опциях `fontspec`. Символ нужно определить в шрифте. При этом, так как ГОСТ иного начертания символа не предлагает (стоит проверить ещё раз), он будет построен просто ссылкой на `epsilon`.
- [x] `\textiota`. Та же проблема.
- [x] `\textphi`. Та же проблема - с var символами.

**Comment by sergey-s-betke** [comment]
По ГОСТ 2.304-81 начертание указанных выше символов только одно предусмотрено. Поэтому следует просто продублировать символы (через ссылку).

**Comment by sergey-s-betke** [comment]
Однако. `\textgamma` генерирует код символа `0x0194` (LATIN CAPITAL LETTER GAMMA)! Во-первых, почему capital? Во-вторых, почему latin, а не greek? Предположу, что latin потому, что при загрузке шрифта `fontspec` указал сам `script=latn`...

Добавление символа в шрифт с указанным кодом решает проблему, но правильное ли это решение?

Попробую явно указать `script=grek` перед греческими символами...

**Comment by sergey-s-betke** [comment]
Указание письма никак проблему не решает. Хотя `fontspec` его корректно транслирует в параметры загружаемого шрифта.

**Comment by sergey-s-betke** [comment]
https://github.com/wspr/unicode-math/issues/349

**Comment by sergey-s-betke** [comment]
Осталось решить вопрос с макросами `\Alpha`, `\Beta` и так далее. Они сейчас приводят к `\mitAlpha`, а не к использованию наклонного шрифта...

**Comment by sergey-s-betke** [comment]
`Unicode-math` переопределяет отдельные макросы `fontspec`:

```
\cs_set:Nn \__fontspec_setmainfont:nn
 {
  \fontspec_set_family:Nnn \rmdefault {#1}{#2}
  \tl_if_eq:onT {\g__fontspec_mathrm_tl} {\rmdefault}
   {
  \fontspec_set_family:Nnn \g__fontspec_mathrm_tl {#1} {#2}
    \SetMathAlphabet\mathrm{normal}\g_fontspec_encoding_tl\g__fontspec_mathrm_tl\mddefault\updefault
    \SetMathAlphabet\mathit{normal}\g_fontspec_encoding_tl\g__fontspec_mathrm_tl\mddefault\itdefault
    \SetMathAlphabet\mathbf{normal}\g_fontspec_encoding_tl\g__fontspec_mathrm_tl\bfdefault\updefault
   }
  \normalfont
  \ignorespaces
 }
```

Стоит воспользоваться этой логикой, возможно, для подмены шрифта для `\mitAlpha` на наклонный шрифт вместо использования отдельного блока Unicode в основном шрифте.

**Comment by sergey-s-betke** [comment]
@wspr, please, help!

I have one question. `\Alpha` and others greek math symbols assigned to `\mitAlpha`. And to special Unicode block in upright font. But with `\setmathfont` I load my font family:

```
\use:x
  {
    \exp_not:N \setmathfont { \tl_use:N \c_@@_mathfont_tl }
      [
        version = \tl_use:N \c_@@_math_version_tl,
        \tl_use:N \g_@@_font_features_tl,
        NFSSFamily = \tl_use:N \c_@@_NFSS_math_family_tl
      ]
  }
```

with two font files - upright font and **slanted** font (not italic). 

Can I redefine `\mitAlpha` with `Unicode-math` **just for my font** for select greek symbols from my slanted font from main greek symbols range (not from math greek italic unicode block)?

**Comment by sergey-s-betke** [comment]
Возможно, придётся формировать отдельный математический шрифт, в котором определять все именно математические блоки. И именно его использовать для математики.

Посмотрю ещё другие шрифты для TeX. В частности, https://github.com/khaledhosny/xits-math определяет отдельные два шрифта - math и math-bold для математики. Возможно - это правильное решение... Хотя бы ради совместимости с pdfTeX (если буду пытаться в дальнейшем обеспечить поддержку...)...

Тогда в отдельном math шрифте как раз придётся "объединить" наклонный, утолщённый и основной шрифты для получения именно математического шрифта...

**Comment by wspr** [comment]
I'm not sure I completely understand. Can't you use the usual `unicode-math` options to select specific ranges? For example: `\setmathfont[range=it]{<slanted font>}`

(The `range` feature is sometimes a bit flaky but for this type of thing I think it's okay.)

**Comment by sergey-s-betke** [comment]
@wspr, thank You for answer.

```
    \setmathfont {GOST2.304-81TypeA-Slanted.ttf}
      [
        version = {eskd},
        range = it
      ]
```

replace `mathit` font, but **does not change** `\Alpha`, `\Beta` and other greek symbols **char Unicode codes**! I must use for greek math symbols not `0x1D6E0-...` range, just `0x391-0x3C9`!

Can I do it with Unicode-math? Or I must rewrite my fonts for other greek math symbols Unicode ranges?

**Comment by sergey-s-betke** [comment]
Всё больше склоняюсь к тому, что мне придётся определять единый математический шрифт. Лучший вариант - скриптом. Шрифт один, потому как в нём должны присутствовать и наклонные математические символы, и "прямые", и утолщённые (с начертанием по типу Б), и обычные (по типу А).

Подожду ответа. Пока закрою другие задачи, и вернусь к этой. Видимо, с математикой действительно придётся для TeX решать в привычном для него стиле.

И, видимо, обеспечу только совместимость с Unicode-math, но определять математический шрифт придётся исключительно средствами fontspec...

**Comment by sergey-s-betke** [comment]
Может быть, посмотреть в сторону `mathspec`?

**Comment by sergey-s-betke** [comment]
Вопрос касается не только греческого алфавита. Он касается и латиницы, и кириллицы. И цифры!

Итак, математический шрифт у нас будет один - на основе типа А. Основные символы - собственно символы шрифта типа А. В дополнение:
- математические наклонные кириллица, латиница, греческие символы, цифры
- математические утолщённые
- математические наклонные утолщённые

Там и других вариантов масса, но в нашем шрифте их нет. И не будет.

**Comment by sergey-s-betke** [comment]
Итого, - есть предложение: версию 0.6 закончить и опубликовать без математики. В документации её объявить как тестовую и недопустимую к применению.

И уже в 0.7 построить отдельный математический шрифт, но - скриптами.
